apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret
    labels:
        app: example-app
type: Opaque
data:
    DB_USERNAME: <path:kv-v2/data/demo#db-user | base64encode>
    DB_PASSWORD: <path:kv-v2/data/demo#db-password | base64encode>
    DB_ROOT_PASSWORD: <path:kv-v2/data/demo#db-root-password | base64encode>
