apiVersion: v1
kind: Secret
metadata:
    name: example-app-secret
    labels:
        app: example-app
type: Opaque
data:
    DB_USERNAME: <test | base64encode>
    DB_PASSWORD: <1234 | base64encode>
    DB_ROOT_PASSWORD: <1234 | base64encode>
